[package]
name = "anne"
version = "0.1.0"
authors = ["Callum Oakley <c.oakley108@gmail.com>"]
edition = "2018"

[dependencies]
failure = "*"
handlebars = "*"
pulldown-cmark = "*"
serde = { version = "*", features = ["derive"] }
toml = "*"
walkdir = "*"
